name: Deploy to develop

on:
  push:
    branches:
      - 'develop'

jobs:
  redeploy_backend:
    name: Deploy Backend to develop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm install -f
          npm run build
        continue-on-error: false

      - name: SSH Into Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 16.16.205.158
          username: ubuntu                 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /thirdx/thirdxBE
            sudo git stash
            sudo git fetch --all
            sudo git checkout develop
            sudo git pull origin develop
            sudo git log -1
            sudo npm install
            sudo pm2 restart therdexBE_QA
