name: Deploy to develop

on:
  push:
    branches:
      - 'develop'

jobs:
  redeploy_backend:
    name: Deploy Backend to develop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm install -f
          npm run build
        continue-on-error: false

      - name: SSH Into Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 16.16.205.158
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /thiredx/thirdxBE
            sudo git stash
            sudo git fetch --all
            sudo git checkout develop
            sudo git pull origin develop
            sudo git log -1
            sudo npm install
             # PM2 app name (change this if needed)
            PM2_APP_NAME="therdexBE_QA"

            # Enable the PM2 app if it's disabled
            if pm2 list | grep -q "$PM2_APP_NAME"; then
              echo "Enabling PM2 app if it's disabled..."
              sudo pm2 enable $PM2_APP_NAME
            fi

            # Restart the PM2 app
            if pm2 list | grep -q "$PM2_APP_NAME"; then
              echo "Restarting existing PM2 app..."
              sudo pm2 restart $PM2_APP_NAME
            else
              echo "Starting PM2 app for the first time..."
              sudo pm2 start npm --name "$PM2_APP_NAME" -- run start
              sudo pm2 save  # optional: save PM2 state for reboot
            fi
